name: SolanaDevMinecraftAstralFoliaMC
version: v2.7.8
main: com.SolanaDevMinecraft.App
api-version: 1.20.1
author: Amauri Bueno dos Santos
website: https://solanadev.com
description: Plugin que permite ver token Solana Dev no Minecraft
folia-compatible: true
folia-supported: true
commands:
  saldo:
    description: Mostra o seu saldo no banco.
    usage: /saldo
  investir:
    description: Realiza um investimento no banco.
    usage: /investir <quantidade>
    aliases: [invest, aplicar]
  solsaldo:
    description: Verifica o saldo da sua carteira Solana.
    usage: /solsaldo
    aliases: [solbalance, solanabalance]
  soltransferir:
    description: Transfere SOL para outro jogador.
    usage: /soltransferir <quantidade> <jogador_destino>
    aliases: [enviarSOL, solenvio, soltransfer]
  compracomsolana:
    description: Compra moedas do jogo usando Solana.
    usage: /compracomsolana <quantidade_SOL>
    aliases: [buycurrency]
  criarcarteira:
    description: Cria uma nova carteira Solana para você.
    usage: /criarcarteira
    aliases: [carteira, solwallet, createwallet]
  comprar_maca:
    description: Compra uma Maçã Encantada.
    usage: /comprar_maca
    aliases: [buyapple]
  comprar_esmeralda:
    description: Compra uma Esmeralda.
    usage: /comprar_esmeralda
    aliases: [buyemerald]
  comprar_diamante:
    description: Compra um Diamante.
    usage: /comprar_diamante
    aliases: [buydiamond]
  comprar_ouro:
    description: Compra uma Barra de Ouro.
    usage: /comprar_ouro
    aliases: [buygold]
  comprar_ferro:
    description: Compra uma Barra de Ferro.
    usage: /comprar_ferro
    aliases: [buyiron]
  comprar_netherite:
    description: Compra uma Barra de Netherite.
    usage: /comprar_netherite
    aliases: [buynetherite]
  comprar_varinha:
    description: Compra uma Varinha Giratória.
    usage: /comprar_varinha
    aliases: [buySpinningWand]
  comprar_lapis:
    description: Compra um Lápis Lazúli.
    usage: /comprar_lapis
    aliases: [buyLapis]
  comprar_quartzo:
    description: Compra um Quartzo.
    usage: /comprar_quartzo
    aliases: [buyQuartz]
  comprar_redstone:
    description: Compra uma Redstone.
    usage: /comprar_redstone
    aliases: [buyRedstone]
  comprar_argila:
    description: Compra um Bloco de Argila.
    usage: /comprar_argila
    aliases: [buyClay]
  comprar_areia:
    description: Compra um Bloco de Areia.
    usage: /comprar_areia
    aliases: [buySandBlock]
  comprar_ferramentas:
    description: Compra todas as Ferramentas.
    usage: /comprar_ferramentas
    aliases: [buyAllTools]
  comprar_comida:
    description: Compra toda a Comida.
    usage: /comprar_comida
    aliases: [buyAllFood]
  comprar_livro:
    description: Compra um Livro Simples.
    usage: /comprar_livro
    aliases: [buySimpleBook]
  comprar_bloco_esmeralda:
    description: Compra um Bloco de Esmeralda.
    usage: /comprar_bloco_esmeralda
    aliases: [buyEmeraldBlock]
  comprar_mapa:
    description: Compra um Mapa Simples.
    usage: /comprar_mapa
    aliases: [buySimpleMap]
  comprar_bussola:
    description: Compra uma Bússola Simples.
    usage: /comprar_bussola
    aliases: [buySimpleCompass]
  comprar_vara_pesca:
    description: Compra uma Vara de Pesca Simples.
    usage: /comprar_vara_pesca
    aliases: [buySimpleFishingRod]
  comprar_balde_peixe:
    description: Balde com peixe Simples.
    usage: /comprar_balde_peixe
    aliases: [buyAxolotlBucket]
  transferirtokengamer:
    description: Transfere moeda do banco para o jogador.
    usage: /transferirtokengamer <quantidade>
  reembolsosolana:
    description: Solicita reembolso de SOL.
    usage: /reembolsosolana <signature>
    aliases: [refundsolana]
  economia:
    description: Gerencia o saldo do jogador (dar, retirar, definir, saldo)
    usage: /economia [give/take/set/balance] [jogador] [valor]
    aliases: [eco]
  banir:
    description: Bane um jogador do servidor.
    usage: /banir [jogador] [motivo]
    aliases: [ban]
  desbanir:
    description: Desbane um jogador do servidor.
    usage: /desbanir [jogador]
    aliases: [unban]
  desbanir-ip:
    description: Desbane um endereço IP do servidor.
    usage: /desbanir-ip [endereço IP]
    aliases: [unban-ip]
  lista-bans:
    description: Lista jogadores e IPs banidos do servidor.
    usage: /lista-bans
    aliases: [list-bans]
  tpa:
    description: Solicita teleporte para outro jogador.
    usage: /tpa [jogador]
  voltar:
    description: Retorna à última posição antes do teleporte ou morte.
    usage: /voltar
    aliases: [back]
  definircasa:
    description: Define a casa do jogador.
    usage: /definircasa <nome>
    aliases: [sethome]
  casa:
    description: Teleporta o jogador para sua casa.
    usage: /casa <nome>
    aliases: [home]
  trancarbau:
    description: Tranca um baú com senha.
    usage: /trancarbau [senha]
    aliases: [lockchest]
  destrancarbau:
    description: Destranca um baú usando uma senha.
    usage: /destrancarbau [senha]
    aliases: [unlockchest]
  tpaceitar:
    description: Aceita um pedido de teleporte.
    usage: /tpaceitar
    aliases: [tpaccept]
  tprecusar:
    description: Recusa um pedido de teleporte.
    usage: /tprecusar
    aliases: [tpdeny]
  resetarcasas:
    description: Reseta todas as casas do servidor.
    usage: /resetarcasas
    aliases: [homereset]
  resetarbaus:
    description: Reseta todas as senhas de baús.
    usage: /resetarbaus
    aliases: [lockchestressettingall]
  comprar_reliquia_nether:
    description: Compra uma Relíquia do Nether.
    usage: /comprar_reliquia_nether
    aliases: [buyNetherRelic]
  comprar_depurador:
    description: Compra um Depurador de Árvore.
    usage: /comprar_depurador
    aliases: [buyTreeDebugger]
  comprar_reliquia_asa:
    description: Compra uma Relíquia de Asa.
    usage: /comprar_reliquia_asa
    aliases: [buyWingRelic]
  comprar_reliquia_bota:
    description: Compra uma Relíquia de Bota.
    usage: /comprar_reliquia_bota
    aliases: [buyBootRelic]
  comprar_machado_thor:
    description: Compra o Machado do Thor.
    usage: /comprar_machado_thor
    aliases: [buyThorAxe]
  limparTrilhaDeLuz:
    description: Limpa a trilha de luz do jogador.
    usage: /limparTrilhaDeLuz
  comprar_kit_shulker:
    description: Compra um Kit Shulker.
    usage: /comprar_kit_shulker
    aliases: [buyShulkerKit]
  escadas:
    description: Compra escadas.
    usage: /escadas <quantidade>
    aliases: [stairs]
  airdrop:
    description: Solicita um airdrop de tokens.
    usage: /airdrop





  
  
  
